# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: CARRT (version 2)
theme: jekyll-theme-cayman
description: > # this means to ignore newlines until "baseurl:"
  Creating a small robotic vehicle capable of autonomously finding its way to a goal.
#baseurl: "" # the subpath of your site, e.g. /blog
#url: "https://igormiktor.github.io/CARRTv2" # the base hostname & protocol for your site
github_username:  igormiktor

# Build settings
markdown: kramdown
